



trigger:
- master

pool:
 vmImage: 'ubuntu-16.04'

variables:
 BuildConfiguration: 'Release'
 

stages:
- stage: 'Build'
  jobs: 
  - job: 


    steps:
       - task: DotNetCoreCLI@2
         displayName: 'Build'
         inputs:
          command: build
          configuration: '--configuration $(BuildConfiguration)'


       - task: DotNetCoreCLI@2
         displayName: 'Restore'
         inputs:
          command: restore      


       - task: DotNetCoreCLI@2
         displayName: 'Publish'
         inputs:
          command: publish
          publishWebProjects: false
          arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
          zipAfterPublish: false
          modifyOutputPath: false 
       - task: PublishBuildArtifacts@1
         displayName: 'Publish Artifact'
         inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)'
          ArtifactName: 'drop'
          publishLocation: Container
         condition: succeededOrFailed()


          

- stage: 'Test'
  jobs:
  - job: 
    steps:
        
        
        

        - task: DownloadBuildArtifacts@0
          displayName: 'Download Artifcats'
          inputs:          
           artifactName: 'drop'
           downloadPath: '$(System.DefaultWorkingDirectory)'
       
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              cd $(System.DefaultWorkingDirectory)/drop
              wget https://chromedriver.storage.googleapis.com/85.0.4183.8700/chromedriver_linux64.zip
              unzip chromedriver_linux64.zip # sudo apt install unzip
              chmod 774 chromedriver
        - task: CmdLine@2
          inputs:
            script: |
              sudo apt-get install chromium-browser
              echo $(System.DefaultWorkingDirectory)
              cd $(System.DefaultWorkingDirectory)/drop
              chmod a+x chromedriver
           
        - task: DotNetCoreCLI@2
          displayName: 'Selenium run'
          inputs:
           command: custom           
           projects: '**/DotNetCoreSeleniumLinux.dll'      
           custom: vstest    
           arguments: '--logger:trx;logfilename=TEST.xml'
           feedsToUse: select

    
        - task: PublishTestResults@2
          displayName: 'Publish run results'
          inputs:
           testResultsFormat: VSTest
           testResultsFiles: '**/TEST.xml'
           mergeTestResults: true
       
     